rails_app1/config/routes.rb
RailsApp1::Application.routes.draw do
  root 'static#home'
  get '/about' => 'static#about'

  get '/cat-pictures(/:number_of_cats)' => 'static#cats', as: 'cats'
  

  

end

rails_app1/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

rails_app1/app/controllers/static_controller.rb
class StaticController < ApplicationController
  def home

  end

  def about
    
  end

  def cats 
    @cats = CatAPI.new.get_images(results_per_page: params[:number_of_cats] || 1)
  end
end

rails_app1/app/helpers/application_helper.rb
module ApplicationHelper
end

rails_app1/app/helpers/static_helper.rb
module StaticHelper
   def full_title(page_title = '')
    base_title = "Cat Pic Generator"
    if page_title.empty?
      base_title
    else
      "#{page_title} | #{base_title}"
    end
  end
end

rails_app1/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
   <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

<div class="layer">
  <span class="menu">Menu</span>
  <ul>
    <li><%= link_to 'Home', root_path %></li>
    <li><%= link_to 'About', about_path %></li>
    <li><%= link_to 'Cat Pictures', cats_path %></li>
  </ul>
</div>

</body>
</html>